//go:build !ignore_autogenerated

/*
Copyright 2020 The Upbound Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupQuery) DeepCopyInto(out *GroupQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(QuerySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(QueryResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupQuery.
func (in *GroupQuery) DeepCopy() *GroupQuery {
	if in == nil {
		return nil
	}
	out := new(GroupQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Query) DeepCopyInto(out *Query) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(QuerySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(QueryResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Query.
func (in *Query) DeepCopy() *Query {
	if in == nil {
		return nil
	}
	out := new(Query)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Query) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryCondition) DeepCopyInto(out *QueryCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryCondition.
func (in *QueryCondition) DeepCopy() *QueryCondition {
	if in == nil {
		return nil
	}
	out := new(QueryCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryFilter) DeepCopyInto(out *QueryFilter) {
	*out = *in
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]QueryCondition, len(*in))
		copy(*out, *in)
	}
	if in.Owners != nil {
		in, out := &in.Owners, &out.Owners
		*out = make([]QueryOwner, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryFilter.
func (in *QueryFilter) DeepCopy() *QueryFilter {
	if in == nil {
		return nil
	}
	out := new(QueryFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryFilterControlPlane) DeepCopyInto(out *QueryFilterControlPlane) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryFilterControlPlane.
func (in *QueryFilterControlPlane) DeepCopy() *QueryFilterControlPlane {
	if in == nil {
		return nil
	}
	out := new(QueryFilterControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryNestedResources) DeepCopyInto(out *QueryNestedResources) {
	*out = *in
	in.QueryResources.DeepCopyInto(&out.QueryResources)
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryNestedResources.
func (in *QueryNestedResources) DeepCopy() *QueryNestedResources {
	if in == nil {
		return nil
	}
	out := new(QueryNestedResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryObjects) DeepCopyInto(out *QueryObjects) {
	*out = *in
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = (*in).DeepCopy()
	}
	if in.Relations != nil {
		in, out := &in.Relations, &out.Relations
		*out = make(map[string]QueryRelation, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryObjects.
func (in *QueryObjects) DeepCopy() *QueryObjects {
	if in == nil {
		return nil
	}
	out := new(QueryObjects)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryOrder) DeepCopyInto(out *QueryOrder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryOrder.
func (in *QueryOrder) DeepCopy() *QueryOrder {
	if in == nil {
		return nil
	}
	out := new(QueryOrder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryOwner) DeepCopyInto(out *QueryOwner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryOwner.
func (in *QueryOwner) DeepCopy() *QueryOwner {
	if in == nil {
		return nil
	}
	out := new(QueryOwner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryPage) DeepCopyInto(out *QueryPage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryPage.
func (in *QueryPage) DeepCopy() *QueryPage {
	if in == nil {
		return nil
	}
	out := new(QueryPage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryRelation) DeepCopyInto(out *QueryRelation) {
	*out = *in
	in.QueryNestedResources.DeepCopyInto(&out.QueryNestedResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryRelation.
func (in *QueryRelation) DeepCopy() *QueryRelation {
	if in == nil {
		return nil
	}
	out := new(QueryRelation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResources) DeepCopyInto(out *QueryResources) {
	*out = *in
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = new(QueryObjects)
		(*in).DeepCopyInto(*out)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]QueryOrder, len(*in))
		copy(*out, *in)
	}
	out.Page = in.Page
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResources.
func (in *QueryResources) DeepCopy() *QueryResources {
	if in == nil {
		return nil
	}
	out := new(QueryResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResponse) DeepCopyInto(out *QueryResponse) {
	*out = *in
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.QueryResponseObjects.DeepCopyInto(&out.QueryResponseObjects)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResponse.
func (in *QueryResponse) DeepCopy() *QueryResponse {
	if in == nil {
		return nil
	}
	out := new(QueryResponse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResponseControlPlane) DeepCopyInto(out *QueryResponseControlPlane) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResponseControlPlane.
func (in *QueryResponseControlPlane) DeepCopy() *QueryResponseControlPlane {
	if in == nil {
		return nil
	}
	out := new(QueryResponseControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResponseCursor) DeepCopyInto(out *QueryResponseCursor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResponseCursor.
func (in *QueryResponseCursor) DeepCopy() *QueryResponseCursor {
	if in == nil {
		return nil
	}
	out := new(QueryResponseCursor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResponseMutablePath) DeepCopyInto(out *QueryResponseMutablePath) {
	*out = *in
	out.GroupVersionResource = in.GroupVersionResource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResponseMutablePath.
func (in *QueryResponseMutablePath) DeepCopy() *QueryResponseMutablePath {
	if in == nil {
		return nil
	}
	out := new(QueryResponseMutablePath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResponseObject) DeepCopyInto(out *QueryResponseObject) {
	*out = *in
	if in.MutablePath != nil {
		in, out := &in.MutablePath, &out.MutablePath
		*out = new(QueryResponseMutablePath)
		**out = **in
	}
	if in.ControlPlane != nil {
		in, out := &in.ControlPlane, &out.ControlPlane
		*out = new(QueryResponseControlPlane)
		**out = **in
	}
	if in.Object != nil {
		in, out := &in.Object, &out.Object
		*out = (*in).DeepCopy()
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Relations != nil {
		in, out := &in.Relations, &out.Relations
		*out = make(map[string]QueryResponseRelation, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResponseObject.
func (in *QueryResponseObject) DeepCopy() *QueryResponseObject {
	if in == nil {
		return nil
	}
	out := new(QueryResponseObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResponseObjects) DeepCopyInto(out *QueryResponseObjects) {
	*out = *in
	if in.Cursor != nil {
		in, out := &in.Cursor, &out.Cursor
		*out = new(QueryResponseCursor)
		**out = **in
	}
	if in.Objects != nil {
		in, out := &in.Objects, &out.Objects
		*out = make([]QueryResponseObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResponseObjects.
func (in *QueryResponseObjects) DeepCopy() *QueryResponseObjects {
	if in == nil {
		return nil
	}
	out := new(QueryResponseObjects)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryResponseRelation) DeepCopyInto(out *QueryResponseRelation) {
	*out = *in
	in.QueryResponseObjects.DeepCopyInto(&out.QueryResponseObjects)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryResponseRelation.
func (in *QueryResponseRelation) DeepCopy() *QueryResponseRelation {
	if in == nil {
		return nil
	}
	out := new(QueryResponseRelation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuerySpec) DeepCopyInto(out *QuerySpec) {
	*out = *in
	in.QueryTopLevelResources.DeepCopyInto(&out.QueryTopLevelResources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuerySpec.
func (in *QuerySpec) DeepCopy() *QuerySpec {
	if in == nil {
		return nil
	}
	out := new(QuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryTopLevelFilter) DeepCopyInto(out *QueryTopLevelFilter) {
	*out = *in
	out.ControlPlane = in.ControlPlane
	if in.IDs != nil {
		in, out := &in.IDs, &out.IDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.QueryFilter.DeepCopyInto(&out.QueryFilter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryTopLevelFilter.
func (in *QueryTopLevelFilter) DeepCopy() *QueryTopLevelFilter {
	if in == nil {
		return nil
	}
	out := new(QueryTopLevelFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueryTopLevelResources) DeepCopyInto(out *QueryTopLevelResources) {
	*out = *in
	in.QueryResources.DeepCopyInto(&out.QueryResources)
	in.Filter.DeepCopyInto(&out.Filter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueryTopLevelResources.
func (in *QueryTopLevelResources) DeepCopy() *QueryTopLevelResources {
	if in == nil {
		return nil
	}
	out := new(QueryTopLevelResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpaceQuery) DeepCopyInto(out *SpaceQuery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(QuerySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Response != nil {
		in, out := &in.Response, &out.Response
		*out = new(QueryResponse)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpaceQuery.
func (in *SpaceQuery) DeepCopy() *SpaceQuery {
	if in == nil {
		return nil
	}
	out := new(SpaceQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpaceQuery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
